/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS_1_0;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class NEWBOOK extends javax.swing.JFrame {

    /**
     * Creates new form NEWBOOK
     */
    public NEWBOOK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        S5 = new javax.swing.JSeparator();
        S7 = new javax.swing.JSeparator();
        txt_isbn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        S3 = new javax.swing.JSeparator();
        txt_publisher = new javax.swing.JTextField();
        txt_title = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_author = new javax.swing.JTextField();
        S4 = new javax.swing.JSeparator();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        txt_bookid = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        S6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_addbook = new javax.swing.JTextField();
        btn_clear = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_close1 = new javax.swing.JTextField();
        back = new javax.swing.JPanel();
        backlbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setOpacity(0.89F);

        jPanel1.setBackground(new java.awt.Color(21, 21, 21));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_login.setBackground(new java.awt.Color(0, 255, 255));
        lbl_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(51, 51, 51));
        lbl_login.setText("New Book");
        jPanel1.add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(21, 21, 21));

        S5.setBackground(new java.awt.Color(21, 21, 21));
        S5.setForeground(new java.awt.Color(51, 51, 51));

        S7.setBackground(new java.awt.Color(21, 21, 21));
        S7.setForeground(new java.awt.Color(51, 51, 51));

        txt_isbn.setBackground(new java.awt.Color(21, 21, 21));
        txt_isbn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_isbn.setForeground(new java.awt.Color(204, 204, 204));
        txt_isbn.setText("ISBN");
        txt_isbn.setBorder(null);
        txt_isbn.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_isbnFocusGained(evt);
            }
        });
        txt_isbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_isbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_isbnMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        S3.setBackground(new java.awt.Color(21, 21, 21));
        S3.setForeground(new java.awt.Color(51, 51, 51));

        txt_publisher.setBackground(new java.awt.Color(21, 21, 21));
        txt_publisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_publisher.setForeground(new java.awt.Color(204, 204, 204));
        txt_publisher.setText("Publisher");
        txt_publisher.setBorder(null);
        txt_publisher.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_publisher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_publisherFocusGained(evt);
            }
        });
        txt_publisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_publisherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_publisherMouseExited(evt);
            }
        });

        txt_title.setBackground(new java.awt.Color(21, 21, 21));
        txt_title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_title.setForeground(new java.awt.Color(204, 204, 204));
        txt_title.setText("Title");
        txt_title.setBorder(null);
        txt_title.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_title.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_titleFocusGained(evt);
            }
        });
        txt_title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_titleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_titleMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        txt_author.setBackground(new java.awt.Color(21, 21, 21));
        txt_author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_author.setForeground(new java.awt.Color(204, 204, 204));
        txt_author.setText("Author");
        txt_author.setBorder(null);
        txt_author.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_author.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_authorFocusGained(evt);
            }
        });
        txt_author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_authorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_authorMouseExited(evt);
            }
        });

        S4.setBackground(new java.awt.Color(21, 21, 21));
        S4.setForeground(new java.awt.Color(51, 51, 51));

        S1.setBackground(new java.awt.Color(21, 21, 21));
        S1.setForeground(new java.awt.Color(51, 51, 51));

        S2.setBackground(new java.awt.Color(21, 21, 21));
        S2.setForeground(new java.awt.Color(51, 51, 51));

        txt_bookid.setBackground(new java.awt.Color(21, 21, 21));
        txt_bookid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_bookid.setForeground(new java.awt.Color(204, 204, 204));
        txt_bookid.setText("Book ID");
        txt_bookid.setBorder(null);
        txt_bookid.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bookidFocusGained(evt);
            }
        });
        txt_bookid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_bookidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_bookidMouseExited(evt);
            }
        });

        category.setBackground(new java.awt.Color(21, 21, 21));
        category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category.setForeground(new java.awt.Color(153, 153, 153));
        category.setMaximumRowCount(4);
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Fiction", "Translations", "Magazines", "Languages", "ICT", "Maths", "Biology" }));
        category.setBorder(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        txt_Price.setBackground(new java.awt.Color(21, 21, 21));
        txt_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Price.setForeground(new java.awt.Color(204, 204, 204));
        txt_Price.setText("Price");
        txt_Price.setBorder(null);
        txt_Price.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_Price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PriceFocusGained(evt);
            }
        });
        txt_Price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_PriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_PriceMouseExited(evt);
            }
        });

        S6.setBackground(new java.awt.Color(21, 21, 21));
        S6.setForeground(new java.awt.Color(51, 51, 51));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_publisher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_isbn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_author, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(S6)
                                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(S7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 52, -1, 440));

        btn_addbook.setEditable(false);
        btn_addbook.setBackground(new java.awt.Color(21, 21, 21));
        btn_addbook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_addbook.setForeground(new java.awt.Color(0, 255, 255));
        btn_addbook.setText("               Add");
        btn_addbook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        btn_addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addbookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addbookMouseExited(evt);
            }
        });
        jPanel1.add(btn_addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 190, 30));

        btn_clear.setEditable(false);
        btn_clear.setBackground(new java.awt.Color(21, 21, 21));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(0, 255, 255));
        btn_clear.setText("               Clear");
        btn_clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clearMouseExited(evt);
            }
        });
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 180, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        btn_close1.setEditable(false);
        btn_close1.setBackground(new java.awt.Color(21, 21, 21));
        btn_close1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_close1.setForeground(new java.awt.Color(0, 255, 255));
        btn_close1.setText("  X");
        btn_close1.setBorder(null);
        btn_close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_close1MouseExited(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));

        backlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Left_24px.png"))); // NOI18N
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backlblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 939, Short.MAX_VALUE)
                .addComponent(btn_close1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_close1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jPanel4.setBackground(new java.awt.Color(21, 21, 21));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 240, 10));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/design1.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 310, 520));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/cyanpnl.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 310, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy,xx;
    private void txt_bookidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookidFocusGained
        txt_bookid.setText("");
        S1.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_bookidFocusGained

    private void txt_bookidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_bookidMouseEntered
        txt_bookid.setForeground(new Color(0,236,239));
        S1.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_bookidMouseEntered

    private void txt_bookidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_bookidMouseExited
        txt_bookid.setForeground(new Color(204,204,204));
        S1.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_bookidMouseExited

    private void txt_titleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_titleFocusGained
        txt_title.setText("");
        S2.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_titleFocusGained

    private void txt_titleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_titleMouseEntered
        txt_title.setForeground(new Color(0,236,239));
        S2.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_titleMouseEntered

    private void txt_titleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_titleMouseExited
        txt_title.setForeground(new Color(204,204,204));
        S2.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_titleMouseExited

    private void txt_authorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_authorFocusGained
        txt_author.setText("");
        S3.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_authorFocusGained

    private void txt_authorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_authorMouseEntered
        txt_author.setForeground(new Color(0,236,239));
        S3.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_authorMouseEntered

    private void txt_authorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_authorMouseExited
        txt_author.setForeground(new Color(204,204,204));
        S3.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_authorMouseExited

    private void txt_isbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_isbnFocusGained
        txt_isbn.setText("");
        S5.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_isbnFocusGained

    private void txt_isbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseEntered
        txt_isbn.setForeground(new Color(0,236,239));
        S5.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_isbnMouseEntered

    private void txt_isbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isbnMouseExited
        txt_isbn.setForeground(new Color(204,204,204));
        S5.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_isbnMouseExited

    private void txt_publisherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_publisherFocusGained
        txt_publisher.setText("");
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_publisherFocusGained

    private void txt_publisherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_publisherMouseEntered
        txt_publisher.setForeground(new Color(0,236,239));
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_publisherMouseEntered

    private void txt_publisherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_publisherMouseExited
        txt_publisher.setForeground(new Color(204,204,204));
        S4.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_publisherMouseExited

    private void txt_PriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PriceFocusGained
       txt_Price.setText("");
        S7.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_PriceFocusGained

    private void txt_PriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PriceMouseEntered
        txt_Price.setForeground(new Color(0,236,239));
        S7.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_PriceMouseEntered

    private void txt_PriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PriceMouseExited
        txt_Price.setForeground(new Color(204,204,204));
        S7.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_PriceMouseExited

    private void btn_addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addbookMouseClicked
     
    }//GEN-LAST:event_btn_addbookMouseClicked

    private void btn_addbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addbookMouseEntered
        btn_addbook.setBackground(new Color(0,255,255));
        btn_addbook.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_addbookMouseEntered

    private void btn_addbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addbookMouseExited
       btn_addbook.setBackground(new Color(21,21,21));
       btn_addbook.setForeground(new Color(0,255,255));
    }//GEN-LAST:event_btn_addbookMouseExited

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        txt_bookid.setText(" Book ID");
        txt_title.setText(" Title");
        txt_author.setText(" Author");
        txt_isbn.setText("ISBN");
        txt_publisher.setText("Publisher");
        txt_Price.setText(" Price");
        category.setSelectedItem(" Category");
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseEntered
       btn_clear.setBackground(new Color(0,255,255));
       btn_clear.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_clearMouseEntered

    private void btn_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseExited
        btn_clear.setBackground(new Color(21,21,21));
        btn_clear.setForeground(new Color(0,255,255));
    }//GEN-LAST:event_btn_clearMouseExited

    private void btn_close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_close1MouseClicked

    private void btn_close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close1MouseEntered
        btn_close1.setBackground(new Color(0,236,239));
        btn_close1.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_close1MouseEntered

    private void btn_close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close1MouseExited
        btn_close1.setBackground(new Color(21,21,21));
        btn_close1.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_btn_close1MouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        setOpacity((float)0.89);
    }//GEN-LAST:event_jPanel3MouseReleased

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        dispose();
        LOGIN L = new LOGIN();
        L.setVisible(true);
    }//GEN-LAST:event_backlblMouseClicked

    private void backlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseEntered
        back.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_backlblMouseEntered

    private void backlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseExited
        back.setBackground(new Color(21,21,21));
    }//GEN-LAST:event_backlblMouseExited

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEWBOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEWBOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEWBOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEWBOOK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWBOOK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JSeparator S5;
    private javax.swing.JSeparator S6;
    private javax.swing.JSeparator S7;
    private javax.swing.JPanel back;
    private javax.swing.JLabel backlbl;
    private javax.swing.JTextField btn_addbook;
    private javax.swing.JTextField btn_clear;
    private javax.swing.JTextField btn_close1;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_publisher;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
