/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS_1_0;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class NEWSTUDENT extends javax.swing.JFrame {

    /**
     * Creates new form NEWSTUDENT
     */
    public NEWSTUDENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        S5 = new javax.swing.JSeparator();
        S7 = new javax.swing.JSeparator();
        txt_registerno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        S3 = new javax.swing.JSeparator();
        txt_contactno = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        S4 = new javax.swing.JSeparator();
        S1 = new javax.swing.JSeparator();
        S2 = new javax.swing.JSeparator();
        txt_studentid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox<>();
        txt_academicyear = new javax.swing.JTextField();
        S8 = new javax.swing.JSeparator();
        btn_addstudent = new javax.swing.JTextField();
        btn_clear = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_login1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_close = new javax.swing.JTextField();
        back = new javax.swing.JPanel();
        backlbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 21, 21));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(21, 21, 21));

        S5.setBackground(new java.awt.Color(21, 21, 21));
        S5.setForeground(new java.awt.Color(51, 51, 51));

        S7.setBackground(new java.awt.Color(21, 21, 21));
        S7.setForeground(new java.awt.Color(51, 51, 51));

        txt_registerno.setBackground(new java.awt.Color(21, 21, 21));
        txt_registerno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_registerno.setForeground(new java.awt.Color(204, 204, 204));
        txt_registerno.setText("Register No");
        txt_registerno.setBorder(null);
        txt_registerno.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_registerno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_registernoFocusGained(evt);
            }
        });
        txt_registerno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_registernoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_registernoMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        S3.setBackground(new java.awt.Color(21, 21, 21));
        S3.setForeground(new java.awt.Color(51, 51, 51));

        txt_contactno.setBackground(new java.awt.Color(21, 21, 21));
        txt_contactno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_contactno.setForeground(new java.awt.Color(204, 204, 204));
        txt_contactno.setText("Contact No");
        txt_contactno.setBorder(null);
        txt_contactno.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_contactno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contactnoFocusGained(evt);
            }
        });
        txt_contactno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_contactnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_contactnoMouseExited(evt);
            }
        });

        txt_firstname.setBackground(new java.awt.Color(21, 21, 21));
        txt_firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(204, 204, 204));
        txt_firstname.setText("First name");
        txt_firstname.setBorder(null);
        txt_firstname.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_firstnameFocusGained(evt);
            }
        });
        txt_firstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_firstnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_firstnameMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        txt_lastname.setBackground(new java.awt.Color(21, 21, 21));
        txt_lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_lastname.setForeground(new java.awt.Color(204, 204, 204));
        txt_lastname.setText("Last name");
        txt_lastname.setBorder(null);
        txt_lastname.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lastnameFocusGained(evt);
            }
        });
        txt_lastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_lastnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_lastnameMouseExited(evt);
            }
        });

        S4.setBackground(new java.awt.Color(21, 21, 21));
        S4.setForeground(new java.awt.Color(51, 51, 51));

        S1.setBackground(new java.awt.Color(21, 21, 21));
        S1.setForeground(new java.awt.Color(51, 51, 51));

        S2.setBackground(new java.awt.Color(21, 21, 21));
        S2.setForeground(new java.awt.Color(51, 51, 51));

        txt_studentid.setBackground(new java.awt.Color(21, 21, 21));
        txt_studentid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_studentid.setForeground(new java.awt.Color(204, 204, 204));
        txt_studentid.setText("Student ID");
        txt_studentid.setBorder(null);
        txt_studentid.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_studentidFocusGained(evt);
            }
        });
        txt_studentid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_studentidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_studentidMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Enter_24px.png"))); // NOI18N

        semester.setBackground(new java.awt.Color(21, 21, 21));
        semester.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        semester.setForeground(new java.awt.Color(153, 153, 153));
        semester.setMaximumRowCount(4);
        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Semester", "2nd Semester", "3rd Semester" }));
        semester.setBorder(null);

        txt_academicyear.setBackground(new java.awt.Color(21, 21, 21));
        txt_academicyear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_academicyear.setForeground(new java.awt.Color(204, 204, 204));
        txt_academicyear.setText("Academic Year");
        txt_academicyear.setBorder(null);
        txt_academicyear.setMargin(new java.awt.Insets(2, 6, 2, 8));
        txt_academicyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_academicyearFocusGained(evt);
            }
        });
        txt_academicyear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_academicyearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_academicyearMouseExited(evt);
            }
        });

        S8.setBackground(new java.awt.Color(21, 21, 21));
        S8.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txt_studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_registerno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_lastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_contactno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(semester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_academicyear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(S4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_registerno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(S5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_academicyear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(S7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 62, -1, 450));

        btn_addstudent.setEditable(false);
        btn_addstudent.setBackground(new java.awt.Color(21, 21, 21));
        btn_addstudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_addstudent.setForeground(new java.awt.Color(0, 255, 255));
        btn_addstudent.setText("              Add");
        btn_addstudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        btn_addstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addstudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addstudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addstudentMouseExited(evt);
            }
        });
        jPanel1.add(btn_addstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 190, 30));

        btn_clear.setEditable(false);
        btn_clear.setBackground(new java.awt.Color(21, 21, 21));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(0, 255, 255));
        btn_clear.setText("            Clear");
        btn_clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clearMouseExited(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 180, 30));

        jPanel4.setBackground(new java.awt.Color(21, 21, 21));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 240, 10));

        lbl_login1.setBackground(new java.awt.Color(0, 255, 255));
        lbl_login1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_login1.setForeground(new java.awt.Color(51, 51, 51));
        lbl_login1.setText("New Student");
        jPanel1.add(lbl_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        btn_close.setEditable(false);
        btn_close.setBackground(new java.awt.Color(21, 21, 21));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(0, 255, 255));
        btn_close.setText("  X");
        btn_close.setBorder(null);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));

        backlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/icons8_Left_24px.png"))); // NOI18N
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backlblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 939, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/design1.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 310, 520));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS_1_0/IMGS/cyanpnl.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 310, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy,xx;
    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        btn_close.setBackground(new Color(0,236,239));
        btn_close.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        btn_close.setBackground(new Color(21,21,21));
        btn_close.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_btn_closeMouseExited

    private void txt_registernoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_registernoFocusGained
        txt_registerno.setText("");
        S5.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_registernoFocusGained

    private void txt_registernoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registernoMouseEntered
        txt_registerno.setForeground(new Color(0,236,239));
        S5.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_registernoMouseEntered

    private void txt_registernoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registernoMouseExited
        txt_registerno.setForeground(new Color(204,204,204));
        S5.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_registernoMouseExited

    private void txt_contactnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactnoFocusGained
        txt_contactno.setText("");
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_contactnoFocusGained

    private void txt_contactnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contactnoMouseEntered
        txt_contactno.setForeground(new Color(0,236,239));
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_contactnoMouseEntered

    private void txt_contactnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contactnoMouseExited
        txt_contactno.setForeground(new Color(204,204,204));
        S4.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_contactnoMouseExited

    private void txt_firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_firstnameFocusGained
        txt_firstname.setText("");
        S2.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_firstnameFocusGained

    private void txt_firstnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstnameMouseEntered
        txt_firstname.setForeground(new Color(0,236,239));
        S2.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_firstnameMouseEntered

    private void txt_firstnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstnameMouseExited
        txt_firstname.setForeground(new Color(204,204,204));
        S2.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_firstnameMouseExited

    private void txt_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastnameFocusGained
        txt_lastname.setText("");
        S3.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_lastnameFocusGained

    private void txt_lastnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastnameMouseEntered
        txt_lastname.setForeground(new Color(0,236,239));
        S3.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_lastnameMouseEntered

    private void txt_lastnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastnameMouseExited
        txt_lastname.setForeground(new Color(204,204,204));
        S3.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_lastnameMouseExited

    private void txt_studentidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentidFocusGained
        txt_studentid.setText("");
        S1.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_studentidFocusGained

    private void txt_studentidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_studentidMouseEntered
        txt_studentid.setForeground(new Color(0,236,239));
        S1.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_studentidMouseEntered

    private void txt_studentidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_studentidMouseExited
        txt_studentid.setForeground(new Color(204,204,204));
        S1.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_studentidMouseExited

    private void btn_addstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addstudentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addstudentMouseClicked

    private void btn_addstudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addstudentMouseEntered
       btn_addstudent.setBackground(new Color(0,204,204));
       btn_addstudent.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_addstudentMouseEntered

    private void btn_addstudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addstudentMouseExited
       btn_addstudent.setBackground(new Color(21,21,21));
       btn_addstudent.setForeground(new Color(0,204,204));
    }//GEN-LAST:event_btn_addstudentMouseExited

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        txt_studentid.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_registerno.setText("");
        txt_contactno.setText("");
        txt_academicyear.setText("");
        semester.setSelectedItem("");
    }//GEN-LAST:event_btn_clearMouseClicked

    private void btn_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseEntered
       btn_clear.setBackground(new Color(0,204,204));
       btn_clear.setForeground(new Color(21,21,21));
    }//GEN-LAST:event_btn_clearMouseEntered

    private void btn_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseExited
       btn_clear.setBackground(new Color(21,21,21));
       btn_clear.setForeground(new Color(0,204,204));
    }//GEN-LAST:event_btn_clearMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
      setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel3MouseReleased

    private void txt_academicyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_academicyearFocusGained
        txt_academicyear.setText("");
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_academicyearFocusGained

    private void txt_academicyearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_academicyearMouseEntered
        txt_academicyear.setForeground(new Color(0,236,239));
        S4.setForeground(new Color(0,236,239));
    }//GEN-LAST:event_txt_academicyearMouseEntered

    private void txt_academicyearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_academicyearMouseExited
        txt_academicyear.setForeground(new Color(204,204,204));
        S4.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_academicyearMouseExited

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        dispose();
        LOGIN L = new LOGIN();
        L.setVisible(true);
    }//GEN-LAST:event_backlblMouseClicked

    private void backlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseEntered
        back.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_backlblMouseEntered

    private void backlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseExited
        back.setBackground(new Color(21,21,21));
    }//GEN-LAST:event_backlblMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWSTUDENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator S1;
    private javax.swing.JSeparator S2;
    private javax.swing.JSeparator S3;
    private javax.swing.JSeparator S4;
    private javax.swing.JSeparator S5;
    private javax.swing.JSeparator S7;
    private javax.swing.JSeparator S8;
    private javax.swing.JPanel back;
    private javax.swing.JLabel backlbl;
    private javax.swing.JTextField btn_addstudent;
    private javax.swing.JTextField btn_clear;
    private javax.swing.JTextField btn_close;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_login1;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JTextField txt_academicyear;
    private javax.swing.JTextField txt_contactno;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_registerno;
    private javax.swing.JTextField txt_studentid;
    // End of variables declaration//GEN-END:variables
}
